### ISSUE TITLE
SpatialJoinQuery self join performance

### ISSUE THREAD

**Issue by kanghq** [DataSystemsLab/GeoSpark#91]
Hi,
I am doing a benchmark on this feature.
I have nearly 1Million Polygons in my RDD.
I tried to self join to find the overlaping polygons.
I tested on AWS EMR with 4 nodes. each node has 4vCPU and 30GB memory.
The total Execution time is around 1 hour.

```
geoPRDD.spatialPartitioning(GridType.RTREE);
geoPRDD.buildIndex(IndexType.RTREE, true);
geoPRDD.indexedRDD.persist(StorageLevel.MEMORY_ONLY());
geoPRDD.spatialPartitionedRDD.persist(StorageLevel.MEMORY_ONLY());
JoinedRDD = JoinQuery.SpatialJoinQuery(geoPRDD, geoPRDD, true, true);
````

But from your paper, the spatial join query should be much faster than expected. Even though your paper used points.

Is that normal costing such a long time for computing and is there any way to boost the performance?

**Comment by jiayuasu** [comment]
@kanghq , please try to increase the number of RDD partitions. You can specify it in any SpatialRDD constructor. More RDD partition number will significantly improve performance.

**Comment by jiayuasu** [comment]
@kanghq 1 hour is way longer than expected. In addition, what kind of polygons are you using? Does each one have lots of vertexes?

**Comment by kanghq** [comment]
I am using rectangles. 
They may border one by one.
Is that the cause of low performance or if R-tree still works in that scenario?

**Comment by kanghq** [comment]
I think I found the problem. I put so much data inside the geometry object. And that causes too much time for serialization.
But I still can't find a good way to include attributes inside the geometry.

**Comment by geoHeil** [comment]
May I add a question here: currently I am experimenting with Points (1.5g csv, 100MB parquet cached in memory, 2-3 Million points) and Polygons (3g Parquet on disk, 100G when 100% cached in memory as PolygonRDD, 4-5 Million polygons).

When performing a join now (currently on a single experimentation node with 850 gb RAM and around 40CPUs  I notice that it is not enough ram and get a full GC 2-3 times.

I already increased partitions to around 3*#cpuCores would you suggest more for this specific use case? The overall runtime is around 2h.

Are there some (memory) settings you suggest for tuning sparks configuration?

**Comment by kanghq** [comment]
I am using PolygonRDD(org.apache.spark.api.java.JavaRDD<com.vividsolutions.jts.geom.Polygon> rawSpatialRDD, org.apache.spark.storage.StorageLevel newLevel)
this constructor and the rawspatialRDD has more than 40 partitions.

**Comment by jiayuasu** [comment]
@kanghq @geoHeil I am not sure why it takes so much time. 

1. Please try to increase the partition again and see how the time changes.

2. If the GC time (you can check it on MasterIP:4040) is very high, for example, more than 10 seconds, the memory is probably not enough. Please set "carryOriginalData" as "false" to see how the time changes. Because the original input data is deserialized in memory and its size is much larger than its disk size. If this is the problem, please use a unique ID instead of Store all original input data.

**Comment by geoHeil** [comment]
@jiayuasu , I will try 1, definitely it is 2(GC), as full GC takes very long. Currently, I use `StorageLevel.MEMORY_ONLY_SER`, but no difference can be reported compared to `StorageLevel.MEMORY_ONLY`, i.e. both times need too much memory.

**Comment by jiayuasu** [comment]
@geoHeil This is one limitation of Spark. All data is deserialized to in a loose format and stored in Java heap. The in memory RDD size becomes super huge after caching. A possible workaround is to use Kyro but I haven't try it yet.

There is one boolean type parameter in SpatialRDD constructor called carryInputData. Please set that as false.

**Comment by geoHeil** [comment]
Kryo per se will probably not help that much but dataframes like magellan
with Tungsten and off heap would be interesting.
Jia Yu <notifications@github.com> schrieb am Mo. 15. Mai 2017 um 07:01:

**Comment by geoHeil** [comment]
Please, could you link me to the snippet. A full text search did not find
this parameter.
Georg Heiler <georg.kf.heiler@gmail.com> schrieb am Mo. 15. Mai 2017 um
07:12:

**Comment by jiayuasu** [comment]
@geoHeil Please check the JavaDoc:http://www.public.asu.edu/~jiayu2/geospark/javadoc/0.6.2/

PointRDD, PolygonRDD, and LineStringRDD constructors have a parameter called "carryInputData"

**Comment by kanghq** [comment]
@geoHeil I am using Kryo and have the same issue with U, no carryinputData and using unique ID in user-data field. not enough memory, GC > threshold , especially when data skew occurs, spilling in-memory takes unbelivable long time.

**Comment by kanghq** [comment]
@jiayuasu I have increased the Max partitions within ur code requried. that is fixed 200 objects per grid.
But spilling in-memory and full gc also occured.
I think one if the reason is data skew when doing cogroup. but the root cause would be too large memory per object.

**Comment by geoHeil** [comment]
Here a link to the parameter in code: https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/java/org/datasyslab/geospark/spatialRDD/PolygonRDD.java#L75

@kanghq, so you did both: set:`carryInputData`to false and increase the grid size? Where can I change the grid size?

**Comment by jiayuasu** [comment]
@kanghq I agree. I think the root cause is the large memory per object. But the data skewness has been handled GeoSpark spatial partitioning.

@geoHeil  The grid size is equal to the size of partition + 1. So mostly, they are the same.

**Comment by jiayuasu** [comment]
@kanghq Does your polygon have lots of vertexes? Please make sure you always use GridType.RTree as spatial partitioning. If slow GC still happens, please don't build index. The spatial index is another storage overhead.

**Comment by geoHeil** [comment]
@jiayuasu I use RTREE with an index.

**Comment by kanghq** [comment]
@geoHeil Yeah, I converted from JavaRDD<Polygon> with Tuple2 as ID in UserData.
@jiayuasu Only 4 vertexes per object. The GC always happens at the stage when joining polygons.
I'm not sure if the lazy evaluation makes the index building delayd to joining stage.

**Comment by jiayuasu** [comment]
@kanghq @geoHeil 

Here is one more thing I forgot to say: you need to unpersist all persisted RDDs when they are no longer useful. 

For example, GeoSpark automatically persists rawSpatialRDD in Spatial RDD constructor so that GeoSpark can do a fast Analyze on the original RDD (just like a DBMS query optimizer). That means if you don't use myRDD.rawSpatialRDD after constructing the original RDD, you need to manually unpersist it. 

I think, this is also needed in @kanghq case. This will save a large chunk of memory space.

Thanks,
Jia

**Comment by geoHeil** [comment]
I think I see a very long processing time for `flatMapToPair at JoinQuery.java:87` Unfortunately persisting to disk does not work due to sparks 2G limit per partition. I tried to increase spark.default.parallelism to insane values, this did not help. Maybe I should repartition (forcibly) the RDD when creating it from a DataFrame.
Do you have any further ideas where I could look into to remove geosparks need for this really large amount of memory?

**Comment by varpande** [comment]
Hi. I had the same issues with large number of polygons (roughly 100 million). As you mentioned I tried increasing the number of partitions, but that did not help. Setting the carryInput flag also did not help. The problem is somewhere in RTREE partitioning. When running the join I noticed that in the select distinct part of the join, the task were given uneven partitions. On average the size of the partitions was somewhere between 40MB to  70MB. But there was one partition that was 2GB in size and the task running on it ran for several hours before crashing with GC overhead limit exceeded error.

I then tried the QUADTREE Partitioning for the same dataset and the join worked fine and was complete in about 1200 seconds.

**Comment by jiayuasu** [comment]
@varpande Hi, this is because the limitation of R-Tree partitioning. GeoSpark uses a sample of the original data to build the R-Tree and then uses tree leaf node boundary as partition boundary. But R-Tree doesn't cover the entire space so that some of the original data do not cover by any partition so that fall in a "overflow" partition. When the original data is very skewed, the overflow partition will be super large.

GeoSpark supports many different spatial partitioning method so that the user can pick whatever he wants to play. But we suggest you use "Quad-Tree" partitioning or "KDB-Tree" partitioning which solve the aforementioned problem perfectly.

**Comment by Corvexmanu** [comment]
Hi @kanghq , I am starting a project by using GeoSpark (or any big spatial data library) to calculate the frontages and setbacks of buildings (polygons). My input datasets are the buildings + cadastral + streets. However, I have some doubts about whether or not it can be scaled up to AWS EMR. I would like to request your advice about the using of this technology or if you can recommend me any other. Thanks.
